# Global flags apply to every world, including overworld, nether and end.
global:
  pvp: true
  explosion-block-damage: true
  block-place: true
  block-break: true
  keep-inventory: false
  mob-spawning: true
  item-drop: true
  item-pickup: true
  enderpearl: true
  mob-target: true
  mob-damage: true
  mob-entry: true
  equipment-durability: true
messages:
  prefix: '&6[WorldShield]&r '
